#!/usr/bin/env python3
"""Fetch citation counts from OpenAlex for each publication DOI.

Reads the `doi` field from every file in `_publications/`, queries OpenAlex
for the current `cited_by_count`, and writes the running total (plus a
per-DOI breakdown) to `_data/citations.yml`. Run on a schedule by
`.github/workflows/update_citations.yml`.
"""
import datetime
import glob
import os
import sys
import time

import requests
import yaml

MAILTO = os.environ.get("OPENALEX_MAILTO", "jeonghwan231118@gmail.com")
PUB_DIR = "_publications"
OUT = "_data/citations.yml"
API = "https://api.openalex.org/works/doi:{doi}"


def load_front_matter(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    try:
        return yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return {}


def get_citations(doi):
    r = requests.get(
        API.format(doi=doi),
        params={"mailto": MAILTO, "select": "cited_by_count"},
        timeout=30,
    )
    r.raise_for_status()
    return r.json().get("cited_by_count")


def main():
    by_doi = {}
    total = 0
    attempted = 0
    for path in sorted(glob.glob(os.path.join(PUB_DIR, "*.md"))):
        doi = load_front_matter(path).get("doi")
        if not doi:
            continue
        attempted += 1
        doi = str(doi).strip()
        try:
            count = get_citations(doi)
            time.sleep(0.2)
        except Exception as exc:  # keep going on a single failure
            print(f"WARN {doi}: {exc}", file=sys.stderr)
            continue
        if count is None:
            continue
        by_doi[doi] = count
        total += count

    # Guard against an API outage clobbering good data with zeros.
    if attempted > 0 and not by_doi:
        sys.exit("ERROR: no DOIs resolved; leaving _data/citations.yml unchanged.")

    data = {
        "total": total,
        "updated": datetime.date.today().isoformat(),
        "source": "OpenAlex",
        "by_doi": by_doi,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/update_citations.py - do not edit by hand.\n")
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True)
    print(f"Wrote {OUT}: total={total} ({len(by_doi)} papers)")


if __name__ == "__main__":
    main()
